# Generated by Django 4.1.7 on 2023-04-07 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=profiles.models.image_upload)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('email', models.EmailField(default='none', max_length=30)),
                ('phone_number', models.CharField(default='none', max_length=15)),
                ('city', models.CharField(default='none', max_length=30)),
                ('gender', models.CharField(default='male', max_length=15)),
                ('education', models.CharField(default='none', max_length=200)),
                ('tecskill', models.CharField(default='none', max_length=200)),
                ('softskill', models.CharField(default='none', max_length=200)),
                ('language', models.CharField(default='none', max_length=200)),
                ('experience', models.CharField(default='none', max_length=400)),
                ('bio', models.TextField(default='none')),
                ('dob', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
