# Generated by Django 4.1.6 on 2023-04-13 13:34

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(default='none', max_length=40, upload_to=profiles.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(default='none', max_length=40, upload_to=profiles.models.user_directory_path),
        ),
    ]
