# Generated by Django 4.1.6 on 2023-04-13 14:30

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_cv_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.png', upload_to=profiles.models.image_upload),
        ),
    ]
