# Generated by Django 4.1.7 on 2023-05-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
