# Generated by Django 4.1.7 on 2023-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='face',
            field=models.CharField(max_length=200),
        ),
    ]
