# Generated by Django 4.1.7 on 2023-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_face_part',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
