# Generated by Django 4.1.7 on 2023-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_last_face_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_face_part',
        ),
    ]
