# Generated by Django 4.1.7 on 2023-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_remove_profile_last_face_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
