# Generated by Django 4.1.7 on 2023-05-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0019_alter_rate_rauser_alter_rate_ra_other'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='face_name',
        ),
        migrations.AlterField(
            model_name='rate',
            name='RAUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='RA_Other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='RAting',
            field=models.IntegerField(default=0),
        ),
    ]
