# Generated by Django 4.1.7 on 2023-06-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_rate_rating_rate_ratingmoralistic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
