# Generated by Django 4.1.7 on 2023-04-19 22:43

from django.db import migrations, models
import features.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Craftsmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user.png', upload_to=features.models.image_upload)),
                ('name', models.CharField(default='none', max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('phone_number', models.IntegerField(default='none', max_length=15)),
                ('profession', models.CharField(default='none', max_length=30)),
                ('address', models.CharField(default='none', max_length=50)),
                ('working_hours', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
