# Generated by Django 4.1.7 on 2023-05-08 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_alter_craftsmen_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAting', models.IntegerField(default='0')),
                ('RADescription', models.TextField(max_length=10000)),
                ('RACraftsmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.craftsmen', verbose_name='Craftsmen ')),
                ('RAUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ')),
            ],
        ),
    ]
