# Generated by Django 4.1.7 on 2023-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='RADescription',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
