# Generated by Django 4.1.7 on 2023-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('ALexandria', 'ALexandria'), ('Ismailia', 'Ismailia')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
