# Generated by Django 4.1.7 on 2023-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_options_job_city_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('Egypt', 'Egypt')], max_length=15),
        ),
    ]
