# Generated by Django 4.1.7 on 2023-04-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_options_apply_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('ALexandria', 'ALexandria'), ('Ismailia', 'Ismailia'), ('Port Said', 'Port Said'), ('Suez', 'Suez'), ('Luxor', 'Luxor'), ('Mansoura', 'Mansoura'), ('El-Mahalla', 'El-Mahalla'), ('Tanta', 'Tanta'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Zagazig', 'Zagazig'), ('Damietta', 'Damietta'), ('Damanhur', 'Damanhur'), ('Minya', 'Minya'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('Hurghada', 'Hurghada'), ('Banha', 'Banha')], max_length=15),
        ),
    ]
